### PR TITLE
Loader clean and comment

### PR DESCRIPTION
**Pull request by MarcBrout**
Cleaning up and Commenting the classes and interfaces found in the loader package.

I renamed the get*Map methods to get*Config because we load a configuration. A map is just a generic container, we need to know what is the purpose of the contained elements through the methods name.

The uml is updated as well.

### CODE REVIEW

**Review by PierreBougon — COMMENTED** [review]
I like the way you renamed the different variables. Updating the UML is a good thing I didn't verify this part I let @puillandre check this part.
Documention seems pretty good at all.

Seems okay to me

**Review by puillandre — CHANGES_REQUESTED** [review]
UML review
#Thread 
*Remove struct thread
*Add ITask
*change name of AthreadManager to AThreadPool
*Add IThreadManager
*AThreadManager:
**Add list of state
**threadWorkFlow is void
#Loader 
*ALoader
**Change attribute to pointer to IConfigLoader and IDLLLoader (not sure for this one)
#Core
*Add ICore
*Move CLient to Network
*ACore:
**Replace: AThreadMangager by AThreadPool
**Remove client
**Add the config file
**Add network
#Module  
*add IModuleManager
*correct all the sub Modules to their correct name and data.
*correct the data storage
*AModuleManager:
**split list of modules in two: Shared modules and Http modules
**move method to the IModuleManager (with correct names)

**Comment by puillandre** [comment]
Some comments  after the commit i did:
#First, the problem of the ATask creation:
*Problem: you need the request and the client:
**You can get the first one from public function in network
**You, until today, can't get the second one. An if you can, how can you say link it to a request ?
*Solution: the network create or set the structure
#Second, naming problem: for modules: we had a selfProtected type, should'nt we call the ASafeSharedModule: ASharedModule, and the ASharedModule the ASelfProtectedModule ?
#Last: need to add / correct comment in file

**Comment by MarcBrout** [comment]
Rename `ASharedModule,` `ASelfProtectedModule ` to `APIProtectedModule`, `UserProtectedModule`

**Comment by ZenoxTek** [comment]
We have to check this following constructor : 
```
ATask(std::unique_ptr<Request> req, Client &client,
              std::vector<std::unique_ptr<AHTTPModule>> executionList);
```
Contained in the ATask.hpp file.
The execution list should be passed as a right reference, unless you are certain that doing a deep copy and not a shadow copy

**Comment by MarcBrout** [comment]
Reworked the module inheritance hierarchy
`AModule ` → `ASharedModule` → `AProtectedModule`
↳ `HTTPModule`
Added Constructors to modules missing one
The uml is updated as well

**Comment by MarcBrout** [comment]
Okay, I approve what did Pierre, shall I merge this request ?

**Review by puillandre — APPROVED** [review]

**Pull request merged**
